### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by belider** [timovv/notion-website-template#10]
Timo, thank you for creating this repo. It simplifies the process of working with Loconotion. 
But the deployment has recently stopped working, could you update to Node.js 16? 

Error message: 
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

**Comment by timovv** [comment]
Fixed in #12
