### ISSUE TITLE
Toggle headings not working in page

### ISSUE THREAD

**Issue by cst0313** [timovv/notion-website-template#6]

**Comment by timovv** [comment]
This template repo is pretty dumb, and doesn’t actually generate the website. The GitHub action just pulls in Loconotion and uses that to build the pages. If it’s not working, maybe try filing an issue over there. But it looks like this may have been fixed upstream in this PR, maybe try re-running the pipeline now?: https://github.com/leoncvlt/loconotion/pull/123
